[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ioc_inspector"          # ⭢ must match the import you use in tests
version = "0.0.0"
description = "Static IOC extractor and scorer for PDFs & Office docs"
