name: Lint & type-check

# ── Run when Python code or config changes ─────────────────────────────
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
     - "ioc_inspector_core/**/*.py"
     - "logger.py"
     - "settings.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install lint deps
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.4.4 mypy==1.10.0 types-requests

    # Ruff: style + static errors (fast)
    - name: Ruff lint
      run: ruff check .

    # Mypy: type-checking (slower but deeper)
    - name: Mypy
      run: mypy ioc_inspector_core logger.py settings.py
